AWSTemplateFormatVersion: 2010-09-09
Description: EC2 Instance with SecurityGroups

Parameters:
   MyKeyName:
     Description: Please select the KeyName
     Type: AWS::EC2::KeyPair::KeyName

Resources:
   DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
       ImageId: ami-0cd3dfa4e37921605
       KeyName: !Ref MyKeyName
       SecurityGroups:
        - default
        - !Ref SSHSecurityGroup

   SSHSecurityGroup:
     Type:  AWS::EC2::SecurityGroup
     Properties:
         GroupDescription: My New SecurityGroups
         SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: 8080
              ToPort: 8080
              CidrIp: 0.0.0.0/0

   MyElasticIP:     
     Type: AWS::EC2::EIP        
     Properties:
        InstanceId: !Ref DevEC2Instance